# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
      - '.github/workflows/Docs.yaml'
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'
      - '.github/workflows/Docs.yaml'
  workflow_dispatch:
    inputs:
      ghpages:
        description: 'Build gitbook with pandoc devel and deploy gitbook to gh-page for checking differences'
        required: false
        default: true

name: Build and deploy book

jobs:
  build:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KNITR_OPTIONS: "knitr.chunk.tidy=TRUE"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        if: ${{ ! github.event.inputs.ghpages }}
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1.1'

      - uses: cderv/actions/setup-pandoc-nightly@nightly-pandoc
        # install nightly when checking on gh-pages
        if: github.event.inputs.ghpages

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Install OS dependencies
        run: |
          brew update
          brew install --cask xquartz
          brew install --cask calibre
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          needs: book

      - name: Install phamtomJS for webshot
        run: |
          webshot::install_phantomjs()
        shell: Rscript {0}

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: docs/_bookdown_files
          key: bookdown-${{ hashFiles('docs/*Rmd') }}
          restore-keys: bookdown-

      - name: Test build of HTML books
        if: github.event_name == 'pull_request'
        run: make -C docs gitbook bs4_book

      - name: Build and Deploy all book
        if: github.event_name == 'push'
        env:
          CONNECT_API_KEY: ${{ secrets.RSC_BOOKDOWN_ORG_TOKEN }}
          CONTENT_ID: 3
        run: make -C docs all

      - name: Build Gitbook only
        env:
          DEPLOY_GH_PAGES: ${{ github.event.inputs.ghpages }}
        if: github.event_name == 'workflow_dispatch'
        run: make -C docs gitbook

      - name: Deploy Gitbook to gh-pages
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.ghpages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/_book

      - name: Upload book folder for debug
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: book-dir
          path: docs
